# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(101113)
$foreground = rgb(B6CFBC)
$color0 = rgb(38393B)
$color1 = rgb(060D14)
$color2 = rgb(071015)
$color3 = rgb(162B20)
$color4 = rgb(182F22)
$color5 = rgb(182F22)
$color6 = rgb(225931)
$color7 = rgb(8EB398)
$color8 = rgb(637D6A)
$color9 = rgb(08121B)
$color10 = rgb(0A151C)
$color11 = rgb(1D392B)
$color12 = rgb(203F2D)
$color13 = rgb(203F2D)
$color14 = rgb(2E7741)
$color15 = rgb(8EB398)
